# Generated by Django 3.2.4 on 2021-07-07 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('barcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('nutriment_url', models.TextField()),
                ('nutri_score', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=150)),
                ('off_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryFoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_rank', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.category')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.food')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='foods',
            field=models.ManyToManyField(through='research.CategoryFoods', to='research.Food'),
        ),
    ]
