# Generated by Django 3.2.4 on 2021-06-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('barcode', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('image_url', models.TextField()),
                ('nutriment_url', models.TextField()),
                ('nutri_score', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=150)),
                ('off_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('foods', models.ManyToManyField(to='research.Food')),
            ],
        ),
    ]
